
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { useQueryClient } from "@tanstack/react-query";
import { Loader2 } from "lucide-react";

interface GoalActionDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    defaultValues: {
        name: string;
        target_amount: number;
        icon: string;
    };
    onSuccess?: () => void;
}

export function GoalActionDialog({ open, onOpenChange, defaultValues, onSuccess }: GoalActionDialogProps) {
    const { user } = useAuth();
    const queryClient = useQueryClient();
    const [loading, setLoading] = useState(false);
    const [name, setName] = useState(defaultValues.name);
    const [amount, setAmount] = useState(defaultValues.target_amount.toString());

    // Update local state when default values change
    if (open && name !== defaultValues.name && !loading) {
        setName(defaultValues.name);
        setAmount(defaultValues.target_amount.toString());
    }

    const handleCreateGoal = async () => {
        if (!user) return;
        setLoading(true);

        try {
            const { error } = await supabase.from("savings_goals").insert({
                user_id: user.id,
                name: name,
                target_amount: parseFloat(amount),
                current_amount: 0,
                icon: defaultValues.icon,
                status: 'active',
                is_manual: true // Flag to indicate it wasn't auto-generated by some other process
            });

            if (error) throw error;

            toast.success("Meta criada com sucesso!");
            queryClient.invalidateQueries({ queryKey: ["savings-goals"] });
            onOpenChange(false);
            if (onSuccess) onSuccess();

        } catch (error: any) {
            toast.error("Erro ao criar meta: " + error.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>🎯 Criar Meta Sugerida</DialogTitle>
                    <DialogDescription>
                        O Coach sugeriu esta meta para você. Confirme os detalhes para criar.
                    </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                    <div className="space-y-2">
                        <Label htmlFor="name">Nome da Meta</Label>
                        <Input
                            id="name"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                        />
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="amount">Valor Alvo (Kz)</Label>
                        <Input
                            id="amount"
                            type="number"
                            value={amount}
                            onChange={(e) => setAmount(e.target.value)}
                        />
                    </div>
                </div>
                <DialogFooter>
                    <Button variant="outline" onClick={() => onOpenChange(false)} disabled={loading}>
                        Cancelar
                    </Button>
                    <Button onClick={handleCreateGoal} disabled={loading} className="gradient-primary">
                        {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                        Criar Meta Agora
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
